services:
  nginx:
    ports:
      - "127.0.0.1:${FORWARD_APP_PORT:-8080}:80"

  db:
    ports:
      - "127.0.0.1:${FORWARD_DB_PORT:-5432}:5432"

  redis:
    ports:
      - "127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379"
