services:
  app:
    build:
      target: base
    restart: always
    ports:
      - "${APP_PORT:-80}:8000"

  worker:
    restart: always

  scheduler:
    restart: always

  db:
    restart: always

  redis:
    restart: always
